// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzcywrnvofhhacyulwam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Y3l3cm52b2ZoaGFjeXVsd2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDI5NjUsImV4cCI6MjA3MjcxODk2NX0.qTjABr4PnAwdg46pyknKWe5CAn_3jOHG_am1KFwgvPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});